### ISSUE TITLE
Cannot fetch repository in v2.1.3

### ISSUE THREAD

**Issue by manuelbieh** [shipitjs/shipit-deploy#105] opened 2016-01-24 17:41 UTC
Hey,

I'm getting an error after upgrading to 2.1.3:
```
'deploy:fetch' errored after 2.95 s
Error: Command failed: /bin/sh -c git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
```

My machine is running on Ubuntu 14.04. Repository is on github (private) and I'm using a keyfile to authenticate.

My config:

```
shipit.initConfig({
    default: {
        workspace: '/home/deploy/karmaplus',
        repositoryUrl: 'git@github.com:manuelbieh/karmaplus.git',
        ignores: ['.git', 'node_modules'],
        keepReleases: 5,
        deleteOnRollback: false,
        key: '~/.ssh/id_rsa',
        shallowClone: true
    },
    dev: {
        deployTo: '/var/apps/karmaplus-dev',
        servers: 'deploy@dev.karmaplus.io',
        configFolder: 'dev',
        branch: 'develop'
    },
});
```

The complete error stack I get is the following:

```
Unhandled rejection Error: Command failed: /bin/sh -c git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
Von github.com:manuelbieh/karmaplus
 * [neuer Branch]    develop    -> shipit/develop
 * [neuer Branch]    master     -> shipit/master
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

When I downgrade to 2.1.2, my deployment works fine. shipit-deploy seems to be using `git fetch --depth=1 shipit -p --tags` instead of `git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"`

The command I was running was just `shipit dev deploy`

**Comment by manuelbieh** [comment] 2016-01-24 17:43
Oh, btw: my git version on the server is 2.4.4

**Comment by phacks** [comment] 2016-01-25 16:52
I encountered the exact same problem: downgrading to 2.1.2 fixed it, and the server is running Git v2.1.4. Hope it can help :)

**Comment by diggy** [comment] 2016-01-27 17:50
I can confirm this bug (using `grunt-shipit`).

The problem is situated [here](https://github.com/shipitjs/shipit-deploy/blob/v2.1.3/tasks/deploy/fetch.js#L98), ll. 98-100.

The relevant commit: https://github.com/shipitjs/shipit-deploy/commit/180d6bc66628d9d20e3959addbd37d07fd671b0e

**Comment by josbeir** [comment] 2016-01-28 14:14
I also confirm this, but only when shallowClone is true.

Another issue is that the workspace doesn't get cleared. This results in an error that some directories already exist when running extra mkdir commands and such.

Reverted to 2.1.2 for now

**Comment by pablocrivella** [comment] 2016-02-03 14:47
+1

**Comment by neoziro** [comment] 2016-02-21 16:30
duplicate of #108

**Closed by neoziro** 2016-02-21 16:30 UTC
